### ISSUE TITLE
Support for jetpack compose beta

### ISSUE THREAD

**Issue by noe** [rjrjr/compose-backstack#46]
Now that Jetpack Compose beta is out, the API should stabilize and the need to continuously update should disappear. At least [from beta01 to beta02](https://android.googlesource.com/platform/frameworks/support/+log/df134e0f94ac70e36764a70dc7fb6a083e0e0fab..52fbd7ed5b07ca4431fa828325a1f8da45b02e51/compose/animation) is seems there were no changes in the existing API.

Is it planned to upgrade compose-backstack to compose beta?

**Comment by zach-klippenstein** [comment]
Working on it.

**Comment by zach-klippenstein** [comment]
Release [0.8.0+beta02](https://github.com/zach-klippenstein/compose-backstack/releases/tag/0.8.0%2Bbeta02) supports compose beta02.
